include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_final_fields: warning

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    always_use_package_imports: true
    avoid_print: true
    avoid_unnecessary_containers: true
    sort_child_properties_last: true
    avoid_empty_else: true
    require_trailing_commas: true
