// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVNAl-Zx3Dp246nNwRQa92Xylj4u4Owg',
    appId: '1:748368307596:android:a94d4a4fc2f306ab93a2a9',
    messagingSenderId: '748368307596',
    projectId: 'drippy-drop-a3120',
    storageBucket: 'drippy-drop-a3120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoLIYWzkaXMTqmacq2dOZTXy0SULr8Mp0',
    appId: '1:922485351198:ios:6b0cfdc53c1c3b6b315f0f',
    messagingSenderId: '922485351198',
    projectId: 'drippy-drop-83f6b',
    storageBucket: 'drippy-drop-83f6b.firebasestorage.app',
    androidClientId: '922485351198-sqvk5qnk3tlak0e89l6uds00ig6lkj6n.apps.googleusercontent.com',
    iosClientId: '922485351198-qdp58h6fjllft0j8le5h9huqr92eu3ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.drippydrop',
  );

}